In [1]:
import numpy as np
import pandas as pd
from matplotlib.patches import Patch
import itertools
import pickle
from matplotlib import pyplot as plt
import datetime
from scipy import optimize
import sys
sys.path.append('../SEIR_full/')
sys.path.append('..')
# import SEIR_full as mdl
import datetime as dt

In [2]:
idan_agg = pd.read_pickle('../Data/parameters_matan/home_stay_by_periods.pickle')

In [4]:
amit_agg_no_work = pd.read_csv('../Data/stay_home/no_work.csv')

In [25]:
amit_agg_no_work

          cell_id       min       max      mean       std
0              11  0.129744  0.584765  0.367208  0.135647
1              21  0.084629  0.602408  0.369674  0.148521
2              22  0.088458  0.619701  0.400354  0.160167
3              23  0.085456  0.547624  0.336712  0.138223
4              24  0.102797  0.540278  0.342243  0.135488
5              29  0.033894  0.495440  0.273250  0.132547
6              31  0.094732  0.587352  0.373972  0.142526
7              32  0.099517  0.577338  0.366782  0.143469
8              41  0.068878  0.575707  0.354129  0.144891
9              42  0.080692  0.595361  0.366040  0.147022
10             43  0.081130  0.604703  0.388791  0.156898
11             44  0.071767  0.613060  0.382769  0.158897
12             51  0.088467  0.585113  0.360038  0.141658
13             61  0.065940  0.658342  0.433423  0.182257
14             62  0.045442  0.619161  0.404505  0.176854
15             71  0.145693  0.583419  0.350528  0.130334
16  11_betshemesh  0.061763  0.724148  0.462250  0.203580
17          51_bb  0.053406  0.548285  0.319899  0.147844
18         51_tlv  0.099490  0.541559  0.327607  0.119459
19        62_arab  0.063858  0.663957  0.375417  0.186359

In [7]:
idan_agg.keys()

dict_keys(['routine', 'no_school', 'no_work', 'hundred_meters', 'seger_bb'])

In [8]:
idan_agg['no_work']

                    min       max      mean       std
county
11             0.129166  0.581292  0.366410  0.134400
21             0.070034  0.619072  0.398014  0.162874
22             0.078058  0.585761  0.363807  0.145492
23             0.086721  0.551411  0.337041  0.136751
24             0.100392  0.543798  0.347011  0.137683
29             0.057289  0.461379  0.212567  0.116583
31             0.095282  0.588513  0.374118  0.142772
32             0.105304  0.567223  0.358923  0.139255
41             0.073621  0.571361  0.353524  0.141923
42             0.079768  0.588886  0.361878  0.145266
43             0.081313  0.614845  0.390530  0.156688
44             0.071586  0.613068  0.383717  0.159248
51             0.090436  0.587105  0.361836  0.141653
61             0.058638  0.655039  0.425968  0.182336
62             0.050967  0.615671  0.406426  0.175510
71             0.158568  0.571235  0.339522  0.126864
11_betshemesh  0.062475  0.724378  0.464455  0.203356
51_bb          0.052762  0.548646  0.319939  0.148047
51_tlv         0.100441  0.540641  0.327573  0.118852
62_arab        0.056128  0.659138  0.371006  0.186902

In [22]:
new_idan = pd.read_pickle('../Data/parameters_matan/taz_home_stay_by_periods_updated.pickle')

In [26]:
amit_agg_no_work['cell_id'] = amit_agg_no_work['cell_id'].astype(str)
idan_agg['no_work'].index = idan_agg['no_work'].index.astype(str)
new_idan['no_work'].index = new_idan['no_work'].index.astype(str)

In [28]:
tmp = idan_agg['no_work'].merge(new_idan['no_work'], left_index=True, right_index=True)
tmp

,min_x,max_x,mean_x,std_x,min_y,max_y,mean_y,std_y
county,,,,,,,,
11,0.129166,0.581292,0.366410,0.134400,0.137665,0.588544,0.372967,0.134413
21,0.070034,0.619072,0.398014,0.162874,0.084629,0.602408,0.369674,0.148521
22,0.078058,0.585761,0.363807,0.145492,0.089694,0.620216,0.401168,0.159949
23,0.086721,0.551411,0.337041,0.136751,0.088534,0.549147,0.338944,0.137758
24,0.100392,0.543798,0.347011,0.137683,0.112499,0.545249,0.349356,0.134023
29,0.057289,0.461379,0.212567,0.116583,0.033894,0.495440,0.273250,0.132547
31,0.095282,0.588513,0.374118,0.142772,0.109517,0.594091,0.384196,0.140198
32,0.105304,0.567223,0.358923,0.139255,0.103515,0.579215,0.369594,0.142832
41,0.073621,0.571361,0.353524,0.141923,0.077134,0.579469,0.359855,0.143607
42,0.079768,0.588886,0.361878,0.145266,0.090957,0.599879,0.373119,0.145381
43,0.081313,0.614845,0.390530,0.156688,0.090859,0.608889,0.395263,0.155237
44,0.071586,0.613068,0.383717,0.159248,0.084082,0.618194,0.390958,0.156789
51,0.090436,0.587105,0.361836,0.141653,0.102126,0.591329,0.369627,0.139535
61,0.058638,0.655039,0.425968,0.182336,0.073644,0.661160,0.438096,0.180754
62,0.050967,0.615671,0.406426,0.175510,0.047770,0.620090,0.405957,0.176422
71,0.158568,0.571235,0.339522,0.126864,0.145693,0.583419,0.350528,0.130334
11_betshemesh,0.062475,0.724378,0.464455,0.203356,0.070494,0.726715,0.467254,0.201686
51_bb,0.052762,0.548646,0.319939,0.148047,0.059830,0.551351,0.324514,0.146841
51_tlv,0.100441,0.540641,0.327573,0.118852,0.114574,0.549238,0.338870,0.117458
62_arab,0.056128,0.659138,0.371006,0.186902,0.063858,0.663957,0.375417,0.186359

In [29]:
agg_fncs = ['min', 'max', 'mean', 'std']
for i in agg_fncs:
    tmp[i] = tmp[i+'_x'] - tmp[i+'_y']
    tmp[i] = tmp[i] / tmp[i+'_x']
tmp = tmp[agg_fncs]
tmp

                    min       max      mean       std
county
11            -0.065794 -0.012477 -0.017896 -0.000090
21            -0.208394  0.026917  0.071204  0.088125
22            -0.149075 -0.058821 -0.102694 -0.099365
23            -0.020908  0.004106 -0.005647 -0.007366
24            -0.120599 -0.002668 -0.006757  0.026583
29             0.408367 -0.073824 -0.285476 -0.136931
31            -0.149396 -0.009479 -0.026936  0.018029
32             0.016985 -0.021141 -0.029730 -0.025690
41            -0.047716 -0.014189 -0.017910 -0.011865
42            -0.140265 -0.018669 -0.031063 -0.000788
43            -0.117403  0.009688 -0.012118  0.009262
44            -0.174564 -0.008360 -0.018870  0.015444
51            -0.129253 -0.007195 -0.021534  0.014950
61            -0.255901 -0.009344 -0.028472  0.008679
62             0.062722 -0.007178  0.001153 -0.005197
71             0.081197 -0.021329 -0.032414 -0.027348
11_betshemesh -0.128356 -0.003226 -0.006028  0.008215
51_bb         -0.133973 -0.004931 -0.014302  0.008151
51_tlv        -0.140708 -0.015901 -0.034487  0.011727
62_arab       -0.137738 -0.007311 -0.011890  0.002906

In [24]:
new_idan['no_work']

                    min       max      mean       std
county
11             0.137665  0.588544  0.372967  0.134413
11_betshemesh  0.070494  0.726715  0.467254  0.201686
21             0.084629  0.602408  0.369674  0.148521
22             0.089694  0.620216  0.401168  0.159949
23             0.088534  0.549147  0.338944  0.137758
24             0.112499  0.545249  0.349356  0.134023
29             0.033894  0.495440  0.273250  0.132547
31             0.109517  0.594091  0.384196  0.140198
32             0.103515  0.579215  0.369594  0.142832
41             0.077134  0.579469  0.359855  0.143607
42             0.090957  0.599879  0.373119  0.145381
43             0.090859  0.608889  0.395263  0.155237
44             0.084082  0.618194  0.390958  0.156789
51             0.102126  0.591329  0.369627  0.139535
51_bb          0.059830  0.551351  0.324514  0.146841
51_tlv         0.114574  0.549238  0.338870  0.117458
61             0.073644  0.661160  0.438096  0.180754
62             0.047770  0.620090  0.405957  0.176422
62_arab        0.063858  0.663957  0.375417  0.186359
71             0.145693  0.583419  0.350528  0.130334